blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name="Заголовок блога")
    slug = models.CharField(max_length=200, verbose_name="URL", blank=True, null=True)
    content = models.TextField(verbose_name="Содержание блога", blank=True, null=True)
    preview = models.ImageField(upload_to="blog/photo", verbose_name="Превью блога", blank=True, null=True)
    created_at = models.DateField(verbose_name="Дата создания", blank=True, null=True)
    published = models.BooleanField(verbose_name="Признак публикации", default=True)
    count_views = models.IntegerField(verbose_name="Количество просмотров", default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

blog/views.py
from django.urls import reverse_lazy, reverse

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogListView(ListView):
    model = Blog
    context_object_name = 'objects_list'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object()
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'published', 'created_at',)
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_record = form.save()
            new_record.slug = slugify(new_record.title)
            new_record.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'published', 'created_at',)

    # success_url = reverse_lazy('blog:blog_update')

    def form_valid(self, form):
        if form.is_valid():
            new_record = form.save()
            new_record.slug = slugify(new_record.title)
            new_record.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удаление статьи</h1>
</div>

<div class="py-12 text-center container">
    <div class="row align-items-center">
        <div class="col-md-8 offset-md-2">
            <div class="card mb-4 box-shadow ">
                <p class="card-text">Хочешь удалить {{object.title}}?</p>
                <div class="card-body">
                    <form class="row" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="col">
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Удалить</button>
                            <a class="btn btn-lg btn-block btn-outline-danger" href="{% url 'blog:blog_list'%}"
                               role="button">ОТМЕНИТЬ</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_create.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form class="row" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="col">
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title | capfirst }} ({{object.slug}})</h4>
                </div>
                {% if object.photo %}
                <img src="{{ blog.preview | media_filter }}" onError="this.src= '/static/images/plug_blog.png'"
                     class="card-img-top" alt="photo">>
                {% endif %}
                <div class="card-body">
                    <p class="text-md-start"> {{object.content | capfirst}}</p>
                </div>
                <p align="left">
                    Количество просмотров: {{object.count_views}}
                </p>
                <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form class="row" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <div class="col">
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <a class="btn btn-primary" href="{% url 'blog:create' %}" role="button">Добавить
            блог</a>
        {% for blog in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ blog.title | capfirst }}</h4>
                </div>
                <img src="{{ blog.preview | media_filter }}" height="400">
                <div class="card-body">
                    <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk%}" role="button">Подробнее</a>
                    <a class="btn btn-primary" href="{% url 'blog:blog_update' blog.pk%}"
                       role="button">Редактировать</a>
                </div>
                <a class="btn btn-primary" href="{% url 'blog:blog_delete' blog.pk%}" role="button">Удалить</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}